### ISSUE TITLE
Question about the routing for test

### ISSUE THREAD

**Issue by tjulyz** [gyang274/capsulesEM#4]
Hi!
Thanks for your kind share of the code. There is a question which makes me confused.
I am not sure whether the EM routing should be executed iteratively when the testing procedure.  From your code, I am finding the differences of EM routing procedures for training and testing. Is it means that for every batch the parameters involved with the EM routing need be initialized and updated as the paper Procedure 1 and the EM_ROUTING in your code? If I am wrong, please correct me.
Thanks a lot!

**Comment by gyang274** [comment]
Hi, @tjulyz ,

I believe the EM routing procedure is the same for training and testing. 

Of course, the parameter is different in every batch, or say, every example. From my understanding, this is why it named as `dynamic` routing. And, yes, the parameters, such as inputs capsules means, variance, routing assignment (R matrix), are initialized and updated every time.

Thank you.
